name: company_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  dio: ^4.0.6
  dartz: ^0.10.1
  cached_network_image: ^3.2.1
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.0+1
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
